version: '3.3'

services:
  streamlit-app:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - ./logs:/app/logs
      - .:/app  # Mount the current directory for live reloading
    environment:
      - PYTHONUNBUFFERED=1
      - WATCHDOG_ENABLED=true
    restart: unless-stopped 